version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: deploy_hooks/before_install.sh
      runas: root
  ApplicationStart:
    - location: deploy_hooks/application_start.sh
      runas: root
  ValidateService:
    - location: deploy_hooks/verify_service.sh
      runas: root
